version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=explora_bolivia
    volumes:
      - postgres-db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: explora_bolivia
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  postgres-db:

